version: '3.8'
services:
  mongo-db:
    container_name: mongo-ctr
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./volumes/mongo:/data/db